### ISSUE TITLE
TypeError when sorting LooseVersions

### ISSUE THREAD

**Issue by jwodder** [effigies/looseversion#6]
Using looseversion 1.0.1 on Python 3.10.6, the following occurs:

```
>>> from looseversion import LooseVersion
>>> versions = ['0.3.1@v0.3.1', '0.3@v0.3', '0.2.2.2@v0.2.2.2', '0.2.2.1@v0.2.2.1', '0.2.2@v0.2.2', '0.2.1.1-2@v0.2.1.1-2', '0.2.1.1-1@v0.2.1.1-1', '0.2-1@v0.2-1']
>>> versions.sort(key=LooseVersion)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/l7/wrkq93d133d8zpn36fmqrq0r0000gn/T/pip-run-mkmcq5k0/looseversion.py", line 135, in __lt__
    c = self._cmp(other)
  File "/var/folders/l7/wrkq93d133d8zpn36fmqrq0r0000gn/T/pip-run-mkmcq5k0/looseversion.py", line 185, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by effigies** [comment]
If there's something actionable here, please reopen.
